@hostname = localhost
@port = 6001
@host = {{hostname}}:{{port}}
@contentType = application/json
@token = eyJhbGciOiJSUzI1NiIsImtpZCI6IjNhNTExNDUxZGU3MjhhMmRmOWUzZmU4ZWM3ZWIwNWVlIiwidHlwIjoiYXQrand0In0.eyJuYmYiOjE1ODAxMjY2MzEsImV4cCI6MTU4MDEzMDIzMSwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NTAwMSIsImF1ZCI6ImVwbC5hcGkiLCJjbGllbnRfaWQiOiJlcGwudWkiLCJzdWIiOiIxIiwiYXV0aF90aW1lIjoxNTgwMTI2NjMxLCJpZHAiOiJsb2NhbCIsInNjb3BlIjpbImVwbC5hcGkiXSwiYW1yIjpbImN1c3RvbSJdfQ.NzlaCf7h1NrYzSYQKBQMbzwxs2s0t9Jt_TVHsEd4NTQHXmJKk5-2-dMzTWUflITfvgGxYM0wUVzJtMTaZ68mwG1KCNeH1lsdgQO1cV45fNneQ0yASj0RcO-DzS7aML8Tw1wcPXsPmkcXFvXz12gTJBbKmkIA35_7z7PbuDzTIuaQivxoU48iJYJTH8oPPvWt5V8Vk7wqm17gQuBQ2huLjuEeCMBE_1hJH8cVHiJ730AfX2n1q3zO-SCwBKKnnTpl_UA4WDhDKIm2CHqTmd5LKy77xmc5AFIH71OlNTyUcWmYWXjT7aFgIFFoTboNIjMe9Y7MaFO3LVC4DiREU9bAXQ


###
POST https://{{host}}/api/account
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "email": "a@b.c",
  "password": "12345678"
}

###
@id = 0
DELETE https://{{host}}/api/account/{{id}}
Authorization: Bearer {{token}}