version: '3.7'

services:
  epl.identityserver:
    image: ${DOCKER_REGISTRY}eplidentityserver
    container_name: epl-identityserver
    build:
      context: .
      dockerfile: epl.IdentityServer/Dockerfile
    networks:
      - epl-network

  epl.api:
    image: ${DOCKER_REGISTRY}eplapi
    container_name: epl-api
    build:
      context: .
      dockerfile: epl.api/Dockerfile
    depends_on:
      - epl.database
      - epl.identityserver
    networks:
      - epl-network

  epl.reactui:
    image: ${DOCKER_REGISTRY}eplreactui
    container_name: epl-reactui
    build:
      context: .
      dockerfile: epl.reactui/Dockerfile
    depends_on:
      - epl.identityserver
    networks:
      - epl-network

  epl.database:
    image: ${DOCKER_REGISTRY}epldatabase
    container_name: epl-database
    build:
      context: .
      dockerfile: epl.infrastructure/database-dockerfile
    networks:
      - epl-network

networks:
  epl-network: