version: '3.4'

services:
  epl.identityserver:
    image: ${DOCKER_REGISTRY}eplidentityserver
    build:
      context: .
      dockerfile: epl.IdentityServer/Dockerfile
    networks:
      - epl-network

  epl.api:
    image: ${DOCKER_REGISTRY}eplapi
    build:
      context: .
      dockerfile: epl.api/Dockerfile
    networks:
      - epl-network

  epl.ui:
    image: ${DOCKER_REGISTRY}eplui
    build:
      context: .
      dockerfile: epl.ui/Dockerfile
    networks:
      - epl-network

networks:
  epl-network: